### ISSUE TITLE
Superfluous type annotation import for List

### ISSUE THREAD

**Issue by klinga** [BookOps-CAT/file-retriever#12]
Starting in Python 3.9 no extra type annotations are needed for lists (your package is 3.10 and up).
```from typing import List``` is superfluous. Sorry, it's a super minor thing.
https://github.com/BookOps-CAT/file-retriever/blob/632723362e225c641298affd143804d8e94f8f0c/file_retriever/_clients.py#L14C1-L14C31

**Comment by charlottekostelic** [comment]
Fixed in #13
